### ISSUE TITLE
Feature Request - Add Custom Examples

### ISSUE THREAD

**Issue by gaurav-sofat** [cslarsen/wpm#1]
While the program allows the user to add custom text-sets using a external JSON-encoded file. This is inconvenient for the following reasons -

* The creation of a JSON encoded file is time consuming and while the format of the external file has been clearly specified, any error might cause the program to break, which would cause the user to go through the tedious process of creating the file again.

* A user might not find it convenient to make a new JSON-encoded file to add just one or two custom examples. Moreover the parameter call needs to be written every time to add the sample texts from the user-specified file

* Another case when the current way hampers the proper use is when the user wishes to maintain a set of sample texts which are updated over time. In this case one might be forced to deal with JSON files every now and then, which is not required.
-----------
A solution to this problem (that I have implemented in [my fork](https://github.com/gaurav-sofat/wpm/tree/add-custom-examples)) can be the inclusion of a script that allows the user to add custom sample texts to the [default data file](https://github.com/cslarsen/wpm/blob/master/wpm/data/examples.json) which can then be used anytime and can be updated over time to the liking of the user too.

A simple CLI can be built that saves that works as an interface to format and encode the example text in the format required so that any user, without any JSON knowledge can also add custom-examples to practice on.

Moreover a simple command line flag can be used, so that such custom examples can be added with ease, as and when required.

**Comment by cslarsen** [comment]
See https://github.com/cslarsen/wpm/pull/2
