### ISSUE TITLE
Request for the use of Ctrl key

### ISSUE THREAD

**Issue by cevhyruz** [cslarsen/wpm#14]
I would like to request a feature, if its possible to add the use of ctrl key. like when I'm correcting a typo, I prefer doing it using ctrl + backspace instead of backspace along all the way to the wrong character. is it possible or is it gonna conflict with the terminal keybindings?

**Comment by cslarsen** [comment]
I'll have a look. It's something I'd like as well, but many key combos are difficult or impossible to read in the terminal.

**Comment by cslarsen** [comment]
OK, so I'm gonna need help with this one. If anyone can help me detect CTRL+keys (especially CTRL+backspace) using the default curses library with CPython, please let me know how. I find curses to be quite flaky to be honest, and not a very easy API to work with.

**Comment by cslarsen** [comment]
I can't see any way to fix this, so unfortunately I'll just close it.
