### ISSUE TITLE
UTF-8 input problems

### ISSUE THREAD

**Issue by cslarsen** [cslarsen/wpm#15]
In general, UTF-8 characters not only do not work properly, hitting one involuntarily will give a warning, obscuring the text. Need to fix that across python 2 and 3.

**Comment by felixwiemuth** [comment]
For me, typing "ö" or "ø" also jumps over two characters in the given text and prints wrong characters on the input.

**Comment by felixwiemuth** [comment]
I use Python 3.6.4 on Linux. It always proceeds by two characters when typing these letters. It is also shown as "wrong" in red but nothing is ignored.
In the following example I have typed "aäüÖ" (that is, always where the cursor is on):
![2018-03-21-232202_856x139_scrot](https://user-images.githubusercontent.com/533601/37740629-b29d0d78-2d5e-11e8-9a43-fede6d078d41.png)

**Comment by cslarsen** [comment]
For Python 3.3+, I believe this has been fixed in commit 8629a9e16a58633131a1d738a63507e8786c0f14.

You can try to clone the repo and type "make run3" to run the Python3 version. If that works, I'll soon prepare an official PyPi release.

**Comment by cslarsen** [comment]
It was fixed in Python 2.7 in commit 6dd9408acc

**Comment by felixwiemuth** [comment]
Thanks, it works!

**Comment by cslarsen** [comment]
Great! Thanks for testing!
