### ISSUE TITLE
--load not working

### ISSUE THREAD

**Issue by ArtyomShalagin** [cslarsen/wpm#29]
Launching wpm with `--load filename` results in `UnboundLocalError: local variable 'quotes' referenced before assignment` at commandline.py:174. This makes sense because `quotes` really was not assigned at this point. It also seems like the order of arguments is wrong: `load_plain_text_quote` takes `filename` as the second argument while `opts.load` is provided as the first argument. After fixing this two things there are no more errors, the text still doesn't load properly but I didn't investigate further. 
I could probably fix that if the bug gets approved.

**Comment by cslarsen** [comment]
I have published wpm v1.50.2 to PyPi that addresses this. I also see there are other bugs related to loading plain text files. For instance, the text IDs are always the same when loading your own files. I will fix that.

Thanks for reporting!

**Comment by cslarsen** [comment]
I've fixed the text IDs in v1.50.3
