### ISSUE TITLE
Please put the cpm as a statistic.

### ISSUE THREAD

**Issue by SomeOneSomeHow** [cslarsen/wpm#34]
Hi,

Amazing job!, I use this, it´s a really useful piece of software.

Only one thing, at least for the people in Spain, the wpm don´t say any (but it´s useful) normally you check your speed based on the CPM, so each time I need to multiply the CPS * 60 seconds.

If you can add this to the statistic will be really appreciated.

Thanks again for this software.

**Comment by cslarsen** [comment]
Thanks! I don't have a lot of time these days for projects like these, but it shouldn't be too difficult. 

The reported WPM is actually a direct translation of the CPS, `wpm = (cps/5.0)*60`, so you can take all the WPM figures and calculate CPS with `cps = (wpm/60.0)*5.0` by hand. It even works for all the statistics as well, as it's just a unit difference.

But yes, I understand that this is cumbersome. Adding a `--cps` command line flag or a config setting shouldn't be hard at all. It's just that I can't promise much more on this at the moment.

Let's keep the issue open, and perhaps someone else can help me out even.

**Comment by cslarsen** [comment]
Hi, if you do `pip install --upgrade wpm` you can now either invoke wpm with `--cps` or you can put the line `cps = 1` in your `.wpmrc` file under the `wpm` section.

Let me know if this works for you!

**Comment by SomeOneSomeHow** [comment]
Thanks for taking the time to update the code.

In my other comment, I was asking for a way to pick the cpm (characters per minute) because at least in my country this is the figure that we use and put on the cv and the companies ask for.

So the original idea is if you can handle to add this too maybe in between the wpm and cps...

Before your last commit I picked the cps and multiply by 60 to pick the number, and it´s ok, now I downloaded the new version and invoke with the --cps and without it and I don´t see any difference at least in both cases the cps appears and it´s calculated.

Again thanks for your time and effort to create this.
Cheers.

**Comment by cslarsen** [comment]
Ah, right, you even wrote CP*M* so it's my bad. If I just change the commit to use CPM everywhere I know use CPS (except the existing one in the top bar) then it would work.

**Comment by cslarsen** [comment]
OK, I've published v1.51.3 om PyPi and tagged it here. Use `--cpm` to enable it, or put the `cpm=1` variable in the config file. If you have it enabled, it will show the score in CPM and stats in CPM. I can update it to output CPM in the top bar while you type as well, but that's all I had time for now. :)

Can you please try it out and let me know if it looks alright?

**Comment by cslarsen** [comment]
Taking that as a yes.
