### ISSUE TITLE
Jump to line

### ISSUE THREAD

**Issue by bayarovici** [cslarsen/wpm#40]
Hello author of this awesome plugin. I am using wpm to load my thesis and proofread it. It works great for that and it has helped me so much spot typos I would have otherwise missed. There is only one feature that I am missing. When I load a text would it be possible to jump to a line when I want to avoid a certain paragraph. This helps on repeatedly running the file when I want to jump to the second or third sentence. Thank you!

**Comment by bayarovici** [comment]
This is good stuff man. Your code was very easy to modify even for a  semi-noob like me. I just added         if str(key) == "1":
            self.position +=100
            self.incorrect -= 1
to the game loop and this doesn't affect the speed measurement, it just jumps 100 characters forward. Which is what I need when I use it to proof read my latex document and I want to jump around.

**Comment by cslarsen** [comment]
Good stuff! :) However, I think this is a very particular case that doesn't merit a feature-addon. Perhaps supporting it through arrow keys would be an idea, though. I don't even think wpm supports documents longer than what the terminal window can display.
