### ISSUE TITLE
Option to launch monochrome

### ISSUE THREAD

**Issue by itsamoreh** [cslarsen/wpm#41]
I would love the option to launch wpm in "monochrome" with just the foreground and background colors so it blends in better with my other terminal windows.

**Comment by itsamoreh** [comment]
I was hoping for a `--monochrome` flag like [reddit terminal viewer](https://github.com/michael-lazar/rtv).

But I can use `~/.wpmrc`.

Thanks!

**Comment by cslarsen** [comment]
Ah, right. Maybe it isn't that hard to support. I'm short on time for even simple stuff like this, so will leave the "help wanted" label here in case anyone wants to add support for it.

**Comment by mandyedi** [comment]
Hi!
I would like to contribute to wpm and I thought this issue would be great for starting.
I see that in config.py there is two color mode (xterm256colors, xtermcolors). Is it enough to use only the xtermcolors for monochrome? For incorrect characters I would swap the black background color with the white foreground color.

**Comment by cslarsen** [comment]
Merged, thanks for the effort!
