### ISSUE TITLE
High cpu usage on idle

### ISSUE THREAD

**Issue by BlackCapCoder** [cslarsen/wpm#46]
Usually, wpm uses about 3% of my cpu just sitting in the background doing nothing. This is unfortunate, but perfectly acceptable.

However, this number seems to skyrocket for short texts! If wpm is run with `wpm --short`, then most of the texts causes it to use around 15%, which is more than I am willing to spend just leaving it in a terminal.

**Comment by BlackCapCoder** [comment]
Actually, this is unrelated to the length of the text. If you have typed a text before then your old score is written at the bottom, and this is what is causing cpu usage to go through the roof.

Because there are fewer short texts the problem is just more likely to occur with `wpm --short`.

**Comment by cslarsen** [comment]
Acknowledged. Should be easy to fix, but I'm not actively working on wpm currently. If you want to try your hand in creating a PR, I can take a look.

**Comment by cslarsen** [comment]
Fixed in 7176965827

This will be part of the next release. Thanks for reporting!
