### ISSUE TITLE
support displaying on vim's or tmux statusline

### ISSUE THREAD

**Issue by cevhyruz** [cslarsen/wpm#8]
hi, I have a feature request.. is it possible to make this display on vim's or tmux statusline?

**Comment by cslarsen** [comment]
Can you please elaborate? Do you run it from vim? I've used it with tmux, but I'm not sure what you mean about displaying anything on the status line.

**Comment by nkabbara** [comment]
Hi @cslarsen! Is it possible to use VIM as the editor?

**Comment by cslarsen** [comment]
> Hi @cslarsen! Is it possible to use VIM as the editor?

Nopes, that would require a complete rewrite.
